/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module BPA_N(clk, A, B, Sum, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output Cout;
  wire Cout;
  output [7:0] Sum;
  wire [7:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire [7:0] _60_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  wire \bpa[0].BPA_1.C_M_1 ;
  wire \bpa[0].BPA_1.C_mux_out ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  wire \bpa[1].BPA_1.C_M_1 ;
  wire \bpa[1].BPA_1.C_mux_out ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  input clk;
  wire clk;
  XNOR2_X1 _100_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_35_)
  );
  XNOR2_X1 _101_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_35_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _102_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_36_)
  );
  NOR2_X1 _103_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_37_)
  );
  NOR2_X1 _104_ (
    .A1(_36_),
    .A2(_37_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _105_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_38_)
  );
  XNOR2_X1 _106_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_38_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _107_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_39_)
  );
  NOR2_X1 _108_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_40_)
  );
  NOR2_X1 _109_ (
    .A1(_39_),
    .A2(_40_),
    .ZN(\bpa[0].BPA_1.C_M_1 )
  );
  XNOR2_X1 _110_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_41_)
  );
  XNOR2_X1 _111_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_41_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  XNOR2_X1 _112_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_42_)
  );
  XNOR2_X1 _113_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_43_)
  );
  XNOR2_X1 _114_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_44_)
  );
  XNOR2_X1 _115_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_45_)
  );
  NOR4_X1 _116_ (
    .A1(_42_),
    .A2(_43_),
    .A3(_44_),
    .A4(_45_),
    .ZN(_46_)
  );
  MUX2_X1 _117_ (
    .A(\bpa[1].BPA_1.C_M_1 ),
    .B(\bpa[0].BPA_1.C_mux_out ),
    .S(_46_),
    .Z(\bpa[1].BPA_1.C_mux_out )
  );
  AOI21_X1 _118_ (
    .A(\bpa[0].BPA_1.C_mux_out ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_47_)
  );
  NOR2_X1 _119_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_48_)
  );
  NOR2_X1 _120_ (
    .A1(_47_),
    .A2(_48_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _121_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_49_)
  );
  XNOR2_X1 _122_ (
    .A(\bpa[0].BPA_1.C_mux_out ),
    .B(_49_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _123_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_50_)
  );
  NOR2_X1 _124_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_51_)
  );
  NOR2_X1 _125_ (
    .A1(_50_),
    .A2(_51_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _126_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_52_)
  );
  XNOR2_X1 _127_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_52_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _128_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_53_)
  );
  NOR2_X1 _129_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_54_)
  );
  NOR2_X1 _130_ (
    .A1(_53_),
    .A2(_54_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _131_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_55_)
  );
  XNOR2_X1 _132_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_55_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _133_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_56_)
  );
  NOR2_X1 _134_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_57_)
  );
  NOR2_X1 _135_ (
    .A1(_56_),
    .A2(_57_),
    .ZN(\bpa[1].BPA_1.C_M_1 )
  );
  XNOR2_X1 _136_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_58_)
  );
  XNOR2_X1 _137_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_58_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  BUF_X2 _138_ (
    .A(_59_),
    .Z(Cout)
  );
  BUF_X2 _139_ (
    .A(_60_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _140_ (
    .A(_60_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _141_ (
    .A(_60_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _142_ (
    .A(_60_[3]),
    .Z(Sum[3])
  );
  BUF_X2 _143_ (
    .A(_60_[4]),
    .Z(Sum[4])
  );
  BUF_X2 _144_ (
    .A(_60_[5]),
    .Z(Sum[5])
  );
  BUF_X2 _145_ (
    .A(_60_[6]),
    .Z(Sum[6])
  );
  BUF_X2 _146_ (
    .A(_60_[7]),
    .Z(Sum[7])
  );
  DFF_X1 _61_ (
    .CK(clk),
    .D(A[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_1_)
  );
  DFF_X1 _62_ (
    .CK(clk),
    .D(A[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_2_)
  );
  DFF_X1 _63_ (
    .CK(clk),
    .D(A[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_3_)
  );
  DFF_X1 _64_ (
    .CK(clk),
    .D(A[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_4_)
  );
  DFF_X1 _65_ (
    .CK(clk),
    .D(A[4]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_5_)
  );
  DFF_X1 _66_ (
    .CK(clk),
    .D(A[5]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_6_)
  );
  DFF_X1 _67_ (
    .CK(clk),
    .D(A[6]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_7_)
  );
  DFF_X1 _68_ (
    .CK(clk),
    .D(A[7]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_8_)
  );
  DFF_X1 _69_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.C_mux_out ),
    .Q(_59_),
    .QN(_9_)
  );
  DFF_X1 _70_ (
    .CK(clk),
    .D(B[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_10_)
  );
  DFF_X1 _71_ (
    .CK(clk),
    .D(B[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_11_)
  );
  DFF_X1 _72_ (
    .CK(clk),
    .D(B[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_12_)
  );
  DFF_X1 _73_ (
    .CK(clk),
    .D(B[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_13_)
  );
  DFF_X1 _74_ (
    .CK(clk),
    .D(B[4]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_14_)
  );
  DFF_X1 _75_ (
    .CK(clk),
    .D(B[5]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_15_)
  );
  DFF_X1 _76_ (
    .CK(clk),
    .D(B[6]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_16_)
  );
  DFF_X1 _77_ (
    .CK(clk),
    .D(B[7]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_17_)
  );
  DFF_X1 _78_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_60_[0]),
    .QN(_18_)
  );
  DFF_X1 _79_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_60_[1]),
    .QN(_19_)
  );
  DFF_X1 _80_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_60_[2]),
    .QN(_20_)
  );
  DFF_X1 _81_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_60_[3]),
    .QN(_21_)
  );
  DFF_X1 _82_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_60_[4]),
    .QN(_22_)
  );
  DFF_X1 _83_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_60_[5]),
    .QN(_23_)
  );
  DFF_X1 _84_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_60_[6]),
    .QN(_24_)
  );
  DFF_X1 _85_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_60_[7]),
    .QN(_0_)
  );
  XNOR2_X1 _86_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_25_)
  );
  XNOR2_X1 _87_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_26_)
  );
  XNOR2_X1 _88_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_27_)
  );
  XNOR2_X1 _89_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_28_)
  );
  NOR4_X1 _90_ (
    .A1(_25_),
    .A2(_26_),
    .A3(_27_),
    .A4(_28_),
    .ZN(_29_)
  );
  MUX2_X1 _91_ (
    .A(\bpa[0].BPA_1.C_M_1 ),
    .B(1'h0),
    .S(_29_),
    .Z(\bpa[0].BPA_1.C_mux_out )
  );
  AOI21_X1 _92_ (
    .A(1'h0),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_30_)
  );
  NOR2_X1 _93_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_31_)
  );
  NOR2_X1 _94_ (
    .A1(_30_),
    .A2(_31_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _95_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_32_)
  );
  XNOR2_X1 _96_ (
    .A(1'h0),
    .B(_32_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _97_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_33_)
  );
  NOR2_X1 _98_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_34_)
  );
  NOR2_X1 _99_ (
    .A1(_33_),
    .A2(_34_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
endmodule
