/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module BPA_N(clk, A, B, Sum, Cout);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output Cout;
  wire Cout;
  output [3:0] Sum;
  wire [3:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire [3:0] _31_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  wire \bpa[0].BPA_1.C_M_1 ;
  wire \bpa[0].BPA_1.C_mux_out ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  input clk;
  wire clk;
  DFF_X1 _32_ (
    .CK(clk),
    .D(A[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_1_)
  );
  DFF_X1 _33_ (
    .CK(clk),
    .D(A[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_2_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(A[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_3_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(A[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_4_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.C_mux_out ),
    .Q(_30_),
    .QN(_5_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(B[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_6_)
  );
  DFF_X1 _38_ (
    .CK(clk),
    .D(B[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_7_)
  );
  DFF_X1 _39_ (
    .CK(clk),
    .D(B[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_8_)
  );
  DFF_X1 _40_ (
    .CK(clk),
    .D(B[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_9_)
  );
  DFF_X1 _41_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_31_[0]),
    .QN(_10_)
  );
  DFF_X1 _42_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_31_[1]),
    .QN(_11_)
  );
  DFF_X1 _43_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_31_[2]),
    .QN(_12_)
  );
  DFF_X1 _44_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_31_[3]),
    .QN(_0_)
  );
  XNOR2_X1 _45_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_13_)
  );
  XNOR2_X1 _46_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_14_)
  );
  XNOR2_X1 _47_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_15_)
  );
  XNOR2_X1 _48_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_16_)
  );
  NOR4_X1 _49_ (
    .A1(_13_),
    .A2(_14_),
    .A3(_15_),
    .A4(_16_),
    .ZN(_17_)
  );
  MUX2_X1 _50_ (
    .A(\bpa[0].BPA_1.C_M_1 ),
    .B(1'h0),
    .S(_17_),
    .Z(\bpa[0].BPA_1.C_mux_out )
  );
  AOI21_X1 _51_ (
    .A(1'h0),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_18_)
  );
  NOR2_X1 _52_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_19_)
  );
  NOR2_X1 _53_ (
    .A1(_18_),
    .A2(_19_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _54_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_20_)
  );
  XNOR2_X1 _55_ (
    .A(1'h0),
    .B(_20_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _56_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_21_)
  );
  NOR2_X1 _57_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_22_)
  );
  NOR2_X1 _58_ (
    .A1(_21_),
    .A2(_22_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _59_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_23_)
  );
  XNOR2_X1 _60_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_23_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _61_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_24_)
  );
  NOR2_X1 _62_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_25_)
  );
  NOR2_X1 _63_ (
    .A1(_24_),
    .A2(_25_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _64_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_26_)
  );
  XNOR2_X1 _65_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_26_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _66_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_27_)
  );
  NOR2_X1 _67_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_28_)
  );
  NOR2_X1 _68_ (
    .A1(_27_),
    .A2(_28_),
    .ZN(\bpa[0].BPA_1.C_M_1 )
  );
  XNOR2_X1 _69_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_29_)
  );
  XNOR2_X1 _70_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_29_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  BUF_X2 _71_ (
    .A(_30_),
    .Z(Cout)
  );
  BUF_X2 _72_ (
    .A(_31_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _73_ (
    .A(_31_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _74_ (
    .A(_31_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _75_ (
    .A(_31_[3]),
    .Z(Sum[3])
  );
endmodule
