/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module BPA_N(clk, A, B, Sum, Cout);
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  output Cout;
  wire Cout;
  output [15:0] Sum;
  wire [15:0] Sum;
  wire _0_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _10_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire [15:0] _118_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire _98_;
  wire _99_;
  wire _9_;
  wire \bpa[0].BPA_1.C_M_1 ;
  wire \bpa[0].BPA_1.C_mux_out ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  wire \bpa[1].BPA_1.C_M_1 ;
  wire \bpa[1].BPA_1.C_mux_out ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  wire \bpa[2].BPA_1.C_M_1 ;
  wire \bpa[2].BPA_1.C_mux_out ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  wire \bpa[3].BPA_1.C_M_1 ;
  wire \bpa[3].BPA_1.C_mux_out ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.cout ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.cout ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.cout ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ;
  wire \bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.sum ;
  input clk;
  wire clk;
  DFF_X1 _119_ (
    .CK(clk),
    .D(A[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_1_)
  );
  DFF_X1 _120_ (
    .CK(clk),
    .D(A[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_2_)
  );
  DFF_X1 _121_ (
    .CK(clk),
    .D(A[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_3_)
  );
  DFF_X1 _122_ (
    .CK(clk),
    .D(A[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_4_)
  );
  DFF_X1 _123_ (
    .CK(clk),
    .D(A[4]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_5_)
  );
  DFF_X1 _124_ (
    .CK(clk),
    .D(A[5]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_6_)
  );
  DFF_X1 _125_ (
    .CK(clk),
    .D(A[6]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_7_)
  );
  DFF_X1 _126_ (
    .CK(clk),
    .D(A[7]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_8_)
  );
  DFF_X1 _127_ (
    .CK(clk),
    .D(A[8]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_9_)
  );
  DFF_X1 _128_ (
    .CK(clk),
    .D(A[9]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_10_)
  );
  DFF_X1 _129_ (
    .CK(clk),
    .D(A[10]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_11_)
  );
  DFF_X1 _130_ (
    .CK(clk),
    .D(A[11]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_12_)
  );
  DFF_X1 _131_ (
    .CK(clk),
    .D(A[12]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_13_)
  );
  DFF_X1 _132_ (
    .CK(clk),
    .D(A[13]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_14_)
  );
  DFF_X1 _133_ (
    .CK(clk),
    .D(A[14]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_15_)
  );
  DFF_X1 _134_ (
    .CK(clk),
    .D(A[15]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_16_)
  );
  DFF_X1 _135_ (
    .CK(clk),
    .D(\bpa[3].BPA_1.C_mux_out ),
    .Q(_117_),
    .QN(_17_)
  );
  DFF_X1 _136_ (
    .CK(clk),
    .D(B[0]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_18_)
  );
  DFF_X1 _137_ (
    .CK(clk),
    .D(B[1]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_19_)
  );
  DFF_X1 _138_ (
    .CK(clk),
    .D(B[2]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_20_)
  );
  DFF_X1 _139_ (
    .CK(clk),
    .D(B[3]),
    .Q(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_21_)
  );
  DFF_X1 _140_ (
    .CK(clk),
    .D(B[4]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_22_)
  );
  DFF_X1 _141_ (
    .CK(clk),
    .D(B[5]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_23_)
  );
  DFF_X1 _142_ (
    .CK(clk),
    .D(B[6]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_24_)
  );
  DFF_X1 _143_ (
    .CK(clk),
    .D(B[7]),
    .Q(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_25_)
  );
  DFF_X1 _144_ (
    .CK(clk),
    .D(B[8]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_26_)
  );
  DFF_X1 _145_ (
    .CK(clk),
    .D(B[9]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_27_)
  );
  DFF_X1 _146_ (
    .CK(clk),
    .D(B[10]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_28_)
  );
  DFF_X1 _147_ (
    .CK(clk),
    .D(B[11]),
    .Q(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_29_)
  );
  DFF_X1 _148_ (
    .CK(clk),
    .D(B[12]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_30_)
  );
  DFF_X1 _149_ (
    .CK(clk),
    .D(B[13]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_31_)
  );
  DFF_X1 _150_ (
    .CK(clk),
    .D(B[14]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_32_)
  );
  DFF_X1 _151_ (
    .CK(clk),
    .D(B[15]),
    .Q(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_33_)
  );
  DFF_X1 _152_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_118_[0]),
    .QN(_34_)
  );
  DFF_X1 _153_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_118_[1]),
    .QN(_35_)
  );
  DFF_X1 _154_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_118_[2]),
    .QN(_36_)
  );
  DFF_X1 _155_ (
    .CK(clk),
    .D(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_118_[3]),
    .QN(_37_)
  );
  DFF_X1 _156_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_118_[4]),
    .QN(_38_)
  );
  DFF_X1 _157_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_118_[5]),
    .QN(_39_)
  );
  DFF_X1 _158_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_118_[6]),
    .QN(_40_)
  );
  DFF_X1 _159_ (
    .CK(clk),
    .D(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_118_[7]),
    .QN(_41_)
  );
  DFF_X1 _160_ (
    .CK(clk),
    .D(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_118_[8]),
    .QN(_42_)
  );
  DFF_X1 _161_ (
    .CK(clk),
    .D(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_118_[9]),
    .QN(_43_)
  );
  DFF_X1 _162_ (
    .CK(clk),
    .D(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_118_[10]),
    .QN(_44_)
  );
  DFF_X1 _163_ (
    .CK(clk),
    .D(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_118_[11]),
    .QN(_45_)
  );
  DFF_X1 _164_ (
    .CK(clk),
    .D(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.sum ),
    .Q(_118_[12]),
    .QN(_46_)
  );
  DFF_X1 _165_ (
    .CK(clk),
    .D(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.sum ),
    .Q(_118_[13]),
    .QN(_47_)
  );
  DFF_X1 _166_ (
    .CK(clk),
    .D(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.sum ),
    .Q(_118_[14]),
    .QN(_48_)
  );
  DFF_X1 _167_ (
    .CK(clk),
    .D(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.sum ),
    .Q(_118_[15]),
    .QN(_0_)
  );
  XNOR2_X1 _168_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_49_)
  );
  XNOR2_X1 _169_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_50_)
  );
  XNOR2_X1 _170_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_51_)
  );
  XNOR2_X1 _171_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_52_)
  );
  NOR4_X1 _172_ (
    .A1(_49_),
    .A2(_50_),
    .A3(_51_),
    .A4(_52_),
    .ZN(_53_)
  );
  MUX2_X1 _173_ (
    .A(\bpa[0].BPA_1.C_M_1 ),
    .B(1'h0),
    .S(_53_),
    .Z(\bpa[0].BPA_1.C_mux_out )
  );
  AOI21_X1 _174_ (
    .A(1'h0),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_54_)
  );
  NOR2_X1 _175_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_55_)
  );
  NOR2_X1 _176_ (
    .A1(_54_),
    .A2(_55_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _177_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_56_)
  );
  XNOR2_X1 _178_ (
    .A(1'h0),
    .B(_56_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _179_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_57_)
  );
  NOR2_X1 _180_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_58_)
  );
  NOR2_X1 _181_ (
    .A1(_57_),
    .A2(_58_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _182_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_59_)
  );
  XNOR2_X1 _183_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_59_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _184_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_60_)
  );
  NOR2_X1 _185_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_61_)
  );
  NOR2_X1 _186_ (
    .A1(_60_),
    .A2(_61_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _187_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_62_)
  );
  XNOR2_X1 _188_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_62_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _189_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_63_)
  );
  NOR2_X1 _190_ (
    .A1(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_64_)
  );
  NOR2_X1 _191_ (
    .A1(_63_),
    .A2(_64_),
    .ZN(\bpa[0].BPA_1.C_M_1 )
  );
  XNOR2_X1 _192_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_65_)
  );
  XNOR2_X1 _193_ (
    .A(\bpa[0].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_65_),
    .ZN(\bpa[0].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  XNOR2_X1 _194_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_66_)
  );
  XNOR2_X1 _195_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_67_)
  );
  XNOR2_X1 _196_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_68_)
  );
  XNOR2_X1 _197_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_69_)
  );
  NOR4_X1 _198_ (
    .A1(_66_),
    .A2(_67_),
    .A3(_68_),
    .A4(_69_),
    .ZN(_70_)
  );
  MUX2_X1 _199_ (
    .A(\bpa[1].BPA_1.C_M_1 ),
    .B(\bpa[0].BPA_1.C_mux_out ),
    .S(_70_),
    .Z(\bpa[1].BPA_1.C_mux_out )
  );
  AOI21_X1 _200_ (
    .A(\bpa[0].BPA_1.C_mux_out ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_71_)
  );
  NOR2_X1 _201_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_72_)
  );
  NOR2_X1 _202_ (
    .A1(_71_),
    .A2(_72_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _203_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_73_)
  );
  XNOR2_X1 _204_ (
    .A(\bpa[0].BPA_1.C_mux_out ),
    .B(_73_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _205_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_74_)
  );
  NOR2_X1 _206_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_75_)
  );
  NOR2_X1 _207_ (
    .A1(_74_),
    .A2(_75_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _208_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_76_)
  );
  XNOR2_X1 _209_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_76_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _210_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_77_)
  );
  NOR2_X1 _211_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_78_)
  );
  NOR2_X1 _212_ (
    .A1(_77_),
    .A2(_78_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _213_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_79_)
  );
  XNOR2_X1 _214_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_79_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _215_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_80_)
  );
  NOR2_X1 _216_ (
    .A1(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_81_)
  );
  NOR2_X1 _217_ (
    .A1(_80_),
    .A2(_81_),
    .ZN(\bpa[1].BPA_1.C_M_1 )
  );
  XNOR2_X1 _218_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_82_)
  );
  XNOR2_X1 _219_ (
    .A(\bpa[1].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_82_),
    .ZN(\bpa[1].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  XNOR2_X1 _220_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_83_)
  );
  XNOR2_X1 _221_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_84_)
  );
  XNOR2_X1 _222_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_85_)
  );
  XNOR2_X1 _223_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_86_)
  );
  NOR4_X1 _224_ (
    .A1(_83_),
    .A2(_84_),
    .A3(_85_),
    .A4(_86_),
    .ZN(_87_)
  );
  MUX2_X1 _225_ (
    .A(\bpa[2].BPA_1.C_M_1 ),
    .B(\bpa[1].BPA_1.C_mux_out ),
    .S(_87_),
    .Z(\bpa[2].BPA_1.C_mux_out )
  );
  AOI21_X1 _226_ (
    .A(\bpa[1].BPA_1.C_mux_out ),
    .B1(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_88_)
  );
  NOR2_X1 _227_ (
    .A1(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_89_)
  );
  NOR2_X1 _228_ (
    .A1(_88_),
    .A2(_89_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _229_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_90_)
  );
  XNOR2_X1 _230_ (
    .A(\bpa[1].BPA_1.C_mux_out ),
    .B(_90_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _231_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_91_)
  );
  NOR2_X1 _232_ (
    .A1(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_92_)
  );
  NOR2_X1 _233_ (
    .A1(_91_),
    .A2(_92_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _234_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_93_)
  );
  XNOR2_X1 _235_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_93_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _236_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_94_)
  );
  NOR2_X1 _237_ (
    .A1(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_95_)
  );
  NOR2_X1 _238_ (
    .A1(_94_),
    .A2(_95_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _239_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_96_)
  );
  XNOR2_X1 _240_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_96_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _241_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_97_)
  );
  NOR2_X1 _242_ (
    .A1(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_98_)
  );
  NOR2_X1 _243_ (
    .A1(_97_),
    .A2(_98_),
    .ZN(\bpa[2].BPA_1.C_M_1 )
  );
  XNOR2_X1 _244_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_99_)
  );
  XNOR2_X1 _245_ (
    .A(\bpa[2].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_99_),
    .ZN(\bpa[2].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  XNOR2_X1 _246_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_100_)
  );
  XNOR2_X1 _247_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_101_)
  );
  XNOR2_X1 _248_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_102_)
  );
  XNOR2_X1 _249_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_103_)
  );
  NOR4_X1 _250_ (
    .A1(_100_),
    .A2(_101_),
    .A3(_102_),
    .A4(_103_),
    .ZN(_104_)
  );
  MUX2_X1 _251_ (
    .A(\bpa[3].BPA_1.C_M_1 ),
    .B(\bpa[2].BPA_1.C_mux_out ),
    .S(_104_),
    .Z(\bpa[3].BPA_1.C_mux_out )
  );
  AOI21_X1 _252_ (
    .A(\bpa[2].BPA_1.C_mux_out ),
    .B1(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B2(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_105_)
  );
  NOR2_X1 _253_ (
    .A1(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_106_)
  );
  NOR2_X1 _254_ (
    .A1(_105_),
    .A2(_106_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.cout )
  );
  XNOR2_X1 _255_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.b ),
    .ZN(_107_)
  );
  XNOR2_X1 _256_ (
    .A(\bpa[2].BPA_1.C_mux_out ),
    .B(_107_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.sum )
  );
  AOI21_X1 _257_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B1(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B2(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_108_)
  );
  NOR2_X1 _258_ (
    .A1(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_109_)
  );
  NOR2_X1 _259_ (
    .A1(_108_),
    .A2(_109_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.cout )
  );
  XNOR2_X1 _260_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.b ),
    .ZN(_110_)
  );
  XNOR2_X1 _261_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[0].fa_1.cout ),
    .B(_110_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.sum )
  );
  AOI21_X1 _262_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B1(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B2(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_111_)
  );
  NOR2_X1 _263_ (
    .A1(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_112_)
  );
  NOR2_X1 _264_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.cout )
  );
  XNOR2_X1 _265_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.b ),
    .ZN(_113_)
  );
  XNOR2_X1 _266_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[1].fa_1.cout ),
    .B(_113_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.sum )
  );
  AOI21_X1 _267_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B1(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B2(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_114_)
  );
  NOR2_X1 _268_ (
    .A1(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_115_)
  );
  NOR2_X1 _269_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(\bpa[3].BPA_1.C_M_1 )
  );
  XNOR2_X1 _270_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.b ),
    .ZN(_116_)
  );
  XNOR2_X1 _271_ (
    .A(\bpa[3].BPA_1.fa_4_1.ripple[2].fa_1.cout ),
    .B(_116_),
    .ZN(\bpa[3].BPA_1.fa_4_1.ripple[3].fa_1.sum )
  );
  BUF_X2 _272_ (
    .A(_117_),
    .Z(Cout)
  );
  BUF_X2 _273_ (
    .A(_118_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _274_ (
    .A(_118_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _275_ (
    .A(_118_[10]),
    .Z(Sum[10])
  );
  BUF_X2 _276_ (
    .A(_118_[11]),
    .Z(Sum[11])
  );
  BUF_X2 _277_ (
    .A(_118_[12]),
    .Z(Sum[12])
  );
  BUF_X2 _278_ (
    .A(_118_[13]),
    .Z(Sum[13])
  );
  BUF_X2 _279_ (
    .A(_118_[14]),
    .Z(Sum[14])
  );
  BUF_X2 _280_ (
    .A(_118_[15]),
    .Z(Sum[15])
  );
  BUF_X2 _281_ (
    .A(_118_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _282_ (
    .A(_118_[3]),
    .Z(Sum[3])
  );
  BUF_X2 _283_ (
    .A(_118_[4]),
    .Z(Sum[4])
  );
  BUF_X2 _284_ (
    .A(_118_[5]),
    .Z(Sum[5])
  );
  BUF_X2 _285_ (
    .A(_118_[6]),
    .Z(Sum[6])
  );
  BUF_X2 _286_ (
    .A(_118_[7]),
    .Z(Sum[7])
  );
  BUF_X2 _287_ (
    .A(_118_[8]),
    .Z(Sum[8])
  );
  BUF_X2 _288_ (
    .A(_118_[9]),
    .Z(Sum[9])
  );
endmodule
