/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module CSA_N(A, B, clk, Sum, C_out);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output C_out;
  wire C_out;
  output [7:0] Sum;
  wire [7:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire [7:0] _62_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input clk;
  wire clk;
  wire \csa_M[0].csa_1.C_in ;
  wire \csa_M[0].csa_1.C_out ;
  wire \csa_M[0].csa_1.Cout_0 ;
  wire \csa_M[0].csa_1.Cout_1 ;
  wire [3:0] \csa_M[0].csa_1.S ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ;
  wire \csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.c_out ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.sum ;
  wire \csa_M[0].csa_1.fa_4_2.ripple[3].fa_1.sum ;
  wire \fa_4_3.ripple[0].fa_1.a ;
  wire \fa_4_3.ripple[0].fa_1.b ;
  wire \fa_4_3.ripple[0].fa_1.c_out ;
  wire \fa_4_3.ripple[0].fa_1.sum ;
  wire \fa_4_3.ripple[1].fa_1.a ;
  wire \fa_4_3.ripple[1].fa_1.b ;
  wire \fa_4_3.ripple[1].fa_1.c_out ;
  wire \fa_4_3.ripple[1].fa_1.sum ;
  wire \fa_4_3.ripple[2].fa_1.a ;
  wire \fa_4_3.ripple[2].fa_1.b ;
  wire \fa_4_3.ripple[2].fa_1.c_out ;
  wire \fa_4_3.ripple[2].fa_1.sum ;
  wire \fa_4_3.ripple[3].fa_1.a ;
  wire \fa_4_3.ripple[3].fa_1.b ;
  wire \fa_4_3.ripple[3].fa_1.sum ;
  NAND2_X1 _100_ (
    .A1(_28_),
    .A2(_29_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.c_out )
  );
  XNOR2_X1 _101_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.c_out ),
    .ZN(_30_)
  );
  XNOR2_X1 _102_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ),
    .B(_30_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.sum )
  );
  NAND2_X1 _103_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.c_out ),
    .ZN(_31_)
  );
  OAI21_X1 _104_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .ZN(_32_)
  );
  NAND2_X1 _105_ (
    .A1(_31_),
    .A2(_32_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.c_out )
  );
  XNOR2_X1 _106_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.c_out ),
    .ZN(_33_)
  );
  XNOR2_X1 _107_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ),
    .B(_33_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.sum )
  );
  NAND2_X1 _108_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.c_out ),
    .ZN(_34_)
  );
  OAI21_X1 _109_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .ZN(_35_)
  );
  NAND2_X1 _110_ (
    .A1(_34_),
    .A2(_35_),
    .ZN(\csa_M[0].csa_1.Cout_0 )
  );
  XNOR2_X1 _111_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.c_out ),
    .ZN(_36_)
  );
  XNOR2_X1 _112_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ),
    .B(_36_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.sum )
  );
  NAND2_X1 _113_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(1'h1),
    .ZN(_37_)
  );
  OAI21_X1 _114_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ),
    .B1(1'h1),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .ZN(_38_)
  );
  NAND2_X1 _115_ (
    .A1(_37_),
    .A2(_38_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.c_out )
  );
  XNOR2_X1 _116_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .B(1'h1),
    .ZN(_39_)
  );
  XNOR2_X1 _117_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ),
    .B(_39_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.sum )
  );
  NAND2_X1 _118_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.c_out ),
    .ZN(_40_)
  );
  OAI21_X1 _119_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .ZN(_41_)
  );
  NAND2_X1 _120_ (
    .A1(_40_),
    .A2(_41_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.c_out )
  );
  XNOR2_X1 _121_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.c_out ),
    .ZN(_42_)
  );
  XNOR2_X1 _122_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ),
    .B(_42_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.sum )
  );
  NAND2_X1 _123_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.c_out ),
    .ZN(_43_)
  );
  OAI21_X1 _124_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .ZN(_44_)
  );
  NAND2_X1 _125_ (
    .A1(_43_),
    .A2(_44_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.c_out )
  );
  XNOR2_X1 _126_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.c_out ),
    .ZN(_45_)
  );
  XNOR2_X1 _127_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ),
    .B(_45_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.sum )
  );
  NAND2_X1 _128_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.c_out ),
    .ZN(_46_)
  );
  OAI21_X1 _129_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .ZN(_47_)
  );
  NAND2_X1 _130_ (
    .A1(_46_),
    .A2(_47_),
    .ZN(\csa_M[0].csa_1.Cout_1 )
  );
  XNOR2_X1 _131_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.c_out ),
    .ZN(_48_)
  );
  XNOR2_X1 _132_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ),
    .B(_48_),
    .ZN(\csa_M[0].csa_1.fa_4_2.ripple[3].fa_1.sum )
  );
  NAND2_X1 _133_ (
    .A1(\fa_4_3.ripple[0].fa_1.a ),
    .A2(1'h0),
    .ZN(_49_)
  );
  OAI21_X1 _134_ (
    .A(\fa_4_3.ripple[0].fa_1.b ),
    .B1(1'h0),
    .B2(\fa_4_3.ripple[0].fa_1.a ),
    .ZN(_50_)
  );
  NAND2_X1 _135_ (
    .A1(_49_),
    .A2(_50_),
    .ZN(\fa_4_3.ripple[0].fa_1.c_out )
  );
  XNOR2_X1 _136_ (
    .A(\fa_4_3.ripple[0].fa_1.a ),
    .B(1'h0),
    .ZN(_51_)
  );
  XNOR2_X1 _137_ (
    .A(\fa_4_3.ripple[0].fa_1.b ),
    .B(_51_),
    .ZN(\fa_4_3.ripple[0].fa_1.sum )
  );
  NAND2_X1 _138_ (
    .A1(\fa_4_3.ripple[1].fa_1.a ),
    .A2(\fa_4_3.ripple[0].fa_1.c_out ),
    .ZN(_52_)
  );
  OAI21_X1 _139_ (
    .A(\fa_4_3.ripple[1].fa_1.b ),
    .B1(\fa_4_3.ripple[0].fa_1.c_out ),
    .B2(\fa_4_3.ripple[1].fa_1.a ),
    .ZN(_53_)
  );
  NAND2_X1 _140_ (
    .A1(_52_),
    .A2(_53_),
    .ZN(\fa_4_3.ripple[1].fa_1.c_out )
  );
  XNOR2_X1 _141_ (
    .A(\fa_4_3.ripple[1].fa_1.a ),
    .B(\fa_4_3.ripple[0].fa_1.c_out ),
    .ZN(_54_)
  );
  XNOR2_X1 _142_ (
    .A(\fa_4_3.ripple[1].fa_1.b ),
    .B(_54_),
    .ZN(\fa_4_3.ripple[1].fa_1.sum )
  );
  NAND2_X1 _143_ (
    .A1(\fa_4_3.ripple[2].fa_1.a ),
    .A2(\fa_4_3.ripple[1].fa_1.c_out ),
    .ZN(_55_)
  );
  OAI21_X1 _144_ (
    .A(\fa_4_3.ripple[2].fa_1.b ),
    .B1(\fa_4_3.ripple[1].fa_1.c_out ),
    .B2(\fa_4_3.ripple[2].fa_1.a ),
    .ZN(_56_)
  );
  NAND2_X1 _145_ (
    .A1(_55_),
    .A2(_56_),
    .ZN(\fa_4_3.ripple[2].fa_1.c_out )
  );
  XNOR2_X1 _146_ (
    .A(\fa_4_3.ripple[2].fa_1.a ),
    .B(\fa_4_3.ripple[1].fa_1.c_out ),
    .ZN(_57_)
  );
  XNOR2_X1 _147_ (
    .A(\fa_4_3.ripple[2].fa_1.b ),
    .B(_57_),
    .ZN(\fa_4_3.ripple[2].fa_1.sum )
  );
  NAND2_X1 _148_ (
    .A1(\fa_4_3.ripple[3].fa_1.a ),
    .A2(\fa_4_3.ripple[2].fa_1.c_out ),
    .ZN(_58_)
  );
  OAI21_X1 _149_ (
    .A(\fa_4_3.ripple[3].fa_1.b ),
    .B1(\fa_4_3.ripple[2].fa_1.c_out ),
    .B2(\fa_4_3.ripple[3].fa_1.a ),
    .ZN(_59_)
  );
  NAND2_X1 _150_ (
    .A1(_58_),
    .A2(_59_),
    .ZN(\csa_M[0].csa_1.C_in )
  );
  XNOR2_X1 _151_ (
    .A(\fa_4_3.ripple[3].fa_1.a ),
    .B(\fa_4_3.ripple[2].fa_1.c_out ),
    .ZN(_60_)
  );
  XNOR2_X1 _152_ (
    .A(\fa_4_3.ripple[3].fa_1.b ),
    .B(_60_),
    .ZN(\fa_4_3.ripple[3].fa_1.sum )
  );
  BUF_X2 _153_ (
    .A(_61_),
    .Z(C_out)
  );
  BUF_X2 _154_ (
    .A(_62_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _155_ (
    .A(_62_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _156_ (
    .A(_62_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _157_ (
    .A(_62_[3]),
    .Z(Sum[3])
  );
  BUF_X2 _158_ (
    .A(_62_[4]),
    .Z(Sum[4])
  );
  BUF_X2 _159_ (
    .A(_62_[5]),
    .Z(Sum[5])
  );
  BUF_X2 _160_ (
    .A(_62_[6]),
    .Z(Sum[6])
  );
  BUF_X2 _161_ (
    .A(_62_[7]),
    .Z(Sum[7])
  );
  DFF_X1 _63_ (
    .CK(clk),
    .D(B[0]),
    .Q(\fa_4_3.ripple[0].fa_1.b ),
    .QN(_1_)
  );
  DFF_X1 _64_ (
    .CK(clk),
    .D(B[1]),
    .Q(\fa_4_3.ripple[1].fa_1.b ),
    .QN(_2_)
  );
  DFF_X1 _65_ (
    .CK(clk),
    .D(B[2]),
    .Q(\fa_4_3.ripple[2].fa_1.b ),
    .QN(_3_)
  );
  DFF_X1 _66_ (
    .CK(clk),
    .D(B[3]),
    .Q(\fa_4_3.ripple[3].fa_1.b ),
    .QN(_4_)
  );
  DFF_X1 _67_ (
    .CK(clk),
    .D(B[4]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ),
    .QN(_5_)
  );
  DFF_X1 _68_ (
    .CK(clk),
    .D(B[5]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ),
    .QN(_6_)
  );
  DFF_X1 _69_ (
    .CK(clk),
    .D(B[6]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.b ),
    .QN(_7_)
  );
  DFF_X1 _70_ (
    .CK(clk),
    .D(B[7]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.b ),
    .QN(_8_)
  );
  DFF_X1 _71_ (
    .CK(clk),
    .D(\csa_M[0].csa_1.C_out ),
    .Q(_61_),
    .QN(_9_)
  );
  DFF_X1 _72_ (
    .CK(clk),
    .D(A[0]),
    .Q(\fa_4_3.ripple[0].fa_1.a ),
    .QN(_10_)
  );
  DFF_X1 _73_ (
    .CK(clk),
    .D(A[1]),
    .Q(\fa_4_3.ripple[1].fa_1.a ),
    .QN(_11_)
  );
  DFF_X1 _74_ (
    .CK(clk),
    .D(A[2]),
    .Q(\fa_4_3.ripple[2].fa_1.a ),
    .QN(_12_)
  );
  DFF_X1 _75_ (
    .CK(clk),
    .D(A[3]),
    .Q(\fa_4_3.ripple[3].fa_1.a ),
    .QN(_13_)
  );
  DFF_X1 _76_ (
    .CK(clk),
    .D(A[4]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .QN(_14_)
  );
  DFF_X1 _77_ (
    .CK(clk),
    .D(A[5]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .QN(_15_)
  );
  DFF_X1 _78_ (
    .CK(clk),
    .D(A[6]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.a ),
    .QN(_16_)
  );
  DFF_X1 _79_ (
    .CK(clk),
    .D(A[7]),
    .Q(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.a ),
    .QN(_17_)
  );
  DFF_X1 _80_ (
    .CK(clk),
    .D(\fa_4_3.ripple[0].fa_1.sum ),
    .Q(_62_[0]),
    .QN(_18_)
  );
  DFF_X1 _81_ (
    .CK(clk),
    .D(\fa_4_3.ripple[1].fa_1.sum ),
    .Q(_62_[1]),
    .QN(_19_)
  );
  DFF_X1 _82_ (
    .CK(clk),
    .D(\fa_4_3.ripple[2].fa_1.sum ),
    .Q(_62_[2]),
    .QN(_20_)
  );
  DFF_X1 _83_ (
    .CK(clk),
    .D(\fa_4_3.ripple[3].fa_1.sum ),
    .Q(_62_[3]),
    .QN(_21_)
  );
  DFF_X1 _84_ (
    .CK(clk),
    .D(\csa_M[0].csa_1.S [0]),
    .Q(_62_[4]),
    .QN(_22_)
  );
  DFF_X1 _85_ (
    .CK(clk),
    .D(\csa_M[0].csa_1.S [1]),
    .Q(_62_[5]),
    .QN(_23_)
  );
  DFF_X1 _86_ (
    .CK(clk),
    .D(\csa_M[0].csa_1.S [2]),
    .Q(_62_[6]),
    .QN(_24_)
  );
  DFF_X1 _87_ (
    .CK(clk),
    .D(\csa_M[0].csa_1.S [3]),
    .Q(_62_[7]),
    .QN(_0_)
  );
  MUX2_X1 _88_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.sum ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[0].fa_1.sum ),
    .S(\csa_M[0].csa_1.C_in ),
    .Z(\csa_M[0].csa_1.S [0])
  );
  MUX2_X1 _89_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.sum ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[1].fa_1.sum ),
    .S(\csa_M[0].csa_1.C_in ),
    .Z(\csa_M[0].csa_1.S [1])
  );
  MUX2_X1 _90_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[2].fa_1.sum ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[2].fa_1.sum ),
    .S(\csa_M[0].csa_1.C_in ),
    .Z(\csa_M[0].csa_1.S [2])
  );
  MUX2_X1 _91_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[3].fa_1.sum ),
    .B(\csa_M[0].csa_1.fa_4_2.ripple[3].fa_1.sum ),
    .S(\csa_M[0].csa_1.C_in ),
    .Z(\csa_M[0].csa_1.S [3])
  );
  MUX2_X1 _92_ (
    .A(\csa_M[0].csa_1.Cout_0 ),
    .B(\csa_M[0].csa_1.Cout_1 ),
    .S(\csa_M[0].csa_1.C_in ),
    .Z(\csa_M[0].csa_1.C_out )
  );
  NAND2_X1 _93_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .A2(1'h0),
    .ZN(_25_)
  );
  OAI21_X1 _94_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ),
    .B1(1'h0),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .ZN(_26_)
  );
  NAND2_X1 _95_ (
    .A1(_25_),
    .A2(_26_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.c_out )
  );
  XNOR2_X1 _96_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.a ),
    .B(1'h0),
    .ZN(_27_)
  );
  XNOR2_X1 _97_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.b ),
    .B(_27_),
    .ZN(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.sum )
  );
  NAND2_X1 _98_ (
    .A1(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .A2(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.c_out ),
    .ZN(_28_)
  );
  OAI21_X1 _99_ (
    .A(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.b ),
    .B1(\csa_M[0].csa_1.fa_4_1.ripple[0].fa_1.c_out ),
    .B2(\csa_M[0].csa_1.fa_4_1.ripple[1].fa_1.a ),
    .ZN(_29_)
  );
endmodule
