/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module CSA_N(A, B, clk, Sum, C_out);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output C_out;
  wire C_out;
  output [3:0] Sum;
  wire [3:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire [3:0] _26_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input clk;
  wire clk;
  wire \fa_4_3.C_out ;
  wire \fa_4_3.ripple[0].fa_1.a ;
  wire \fa_4_3.ripple[0].fa_1.b ;
  wire \fa_4_3.ripple[0].fa_1.c_out ;
  wire \fa_4_3.ripple[0].fa_1.sum ;
  wire \fa_4_3.ripple[1].fa_1.a ;
  wire \fa_4_3.ripple[1].fa_1.b ;
  wire \fa_4_3.ripple[1].fa_1.c_out ;
  wire \fa_4_3.ripple[1].fa_1.sum ;
  wire \fa_4_3.ripple[2].fa_1.a ;
  wire \fa_4_3.ripple[2].fa_1.b ;
  wire \fa_4_3.ripple[2].fa_1.c_out ;
  wire \fa_4_3.ripple[2].fa_1.sum ;
  wire \fa_4_3.ripple[3].fa_1.a ;
  wire \fa_4_3.ripple[3].fa_1.b ;
  wire \fa_4_3.ripple[3].fa_1.sum ;
  DFF_X1 _27_ (
    .CK(clk),
    .D(B[1]),
    .Q(\fa_4_3.ripple[1].fa_1.b ),
    .QN(_1_)
  );
  DFF_X1 _28_ (
    .CK(clk),
    .D(B[2]),
    .Q(\fa_4_3.ripple[2].fa_1.b ),
    .QN(_2_)
  );
  DFF_X1 _29_ (
    .CK(clk),
    .D(B[3]),
    .Q(\fa_4_3.ripple[3].fa_1.b ),
    .QN(_3_)
  );
  DFF_X1 _30_ (
    .CK(clk),
    .D(A[0]),
    .Q(\fa_4_3.ripple[0].fa_1.a ),
    .QN(_4_)
  );
  DFF_X1 _31_ (
    .CK(clk),
    .D(A[1]),
    .Q(\fa_4_3.ripple[1].fa_1.a ),
    .QN(_5_)
  );
  DFF_X1 _32_ (
    .CK(clk),
    .D(A[2]),
    .Q(\fa_4_3.ripple[2].fa_1.a ),
    .QN(_6_)
  );
  DFF_X1 _33_ (
    .CK(clk),
    .D(A[3]),
    .Q(\fa_4_3.ripple[3].fa_1.a ),
    .QN(_7_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(\fa_4_3.C_out ),
    .Q(_25_),
    .QN(_8_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(\fa_4_3.ripple[0].fa_1.sum ),
    .Q(_26_[0]),
    .QN(_9_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(\fa_4_3.ripple[1].fa_1.sum ),
    .Q(_26_[1]),
    .QN(_10_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(\fa_4_3.ripple[2].fa_1.sum ),
    .Q(_26_[2]),
    .QN(_11_)
  );
  DFF_X1 _38_ (
    .CK(clk),
    .D(\fa_4_3.ripple[3].fa_1.sum ),
    .Q(_26_[3]),
    .QN(_12_)
  );
  DFF_X1 _39_ (
    .CK(clk),
    .D(B[0]),
    .Q(\fa_4_3.ripple[0].fa_1.b ),
    .QN(_0_)
  );
  NAND2_X1 _40_ (
    .A1(\fa_4_3.ripple[0].fa_1.a ),
    .A2(1'h0),
    .ZN(_13_)
  );
  XNOR2_X1 _41_ (
    .A(\fa_4_3.ripple[0].fa_1.a ),
    .B(1'h0),
    .ZN(_14_)
  );
  XNOR2_X1 _42_ (
    .A(\fa_4_3.ripple[0].fa_1.b ),
    .B(_14_),
    .ZN(\fa_4_3.ripple[0].fa_1.sum )
  );
  OAI21_X1 _43_ (
    .A(\fa_4_3.ripple[0].fa_1.b ),
    .B1(1'h0),
    .B2(\fa_4_3.ripple[0].fa_1.a ),
    .ZN(_15_)
  );
  NAND2_X1 _44_ (
    .A1(_13_),
    .A2(_15_),
    .ZN(\fa_4_3.ripple[0].fa_1.c_out )
  );
  NAND2_X1 _45_ (
    .A1(\fa_4_3.ripple[1].fa_1.a ),
    .A2(\fa_4_3.ripple[0].fa_1.c_out ),
    .ZN(_16_)
  );
  XNOR2_X1 _46_ (
    .A(\fa_4_3.ripple[1].fa_1.a ),
    .B(\fa_4_3.ripple[0].fa_1.c_out ),
    .ZN(_17_)
  );
  XNOR2_X1 _47_ (
    .A(\fa_4_3.ripple[1].fa_1.b ),
    .B(_17_),
    .ZN(\fa_4_3.ripple[1].fa_1.sum )
  );
  OAI21_X1 _48_ (
    .A(\fa_4_3.ripple[1].fa_1.b ),
    .B1(\fa_4_3.ripple[0].fa_1.c_out ),
    .B2(\fa_4_3.ripple[1].fa_1.a ),
    .ZN(_18_)
  );
  NAND2_X1 _49_ (
    .A1(_16_),
    .A2(_18_),
    .ZN(\fa_4_3.ripple[1].fa_1.c_out )
  );
  NAND2_X1 _50_ (
    .A1(\fa_4_3.ripple[2].fa_1.a ),
    .A2(\fa_4_3.ripple[1].fa_1.c_out ),
    .ZN(_19_)
  );
  XNOR2_X1 _51_ (
    .A(\fa_4_3.ripple[2].fa_1.a ),
    .B(\fa_4_3.ripple[1].fa_1.c_out ),
    .ZN(_20_)
  );
  XNOR2_X1 _52_ (
    .A(\fa_4_3.ripple[2].fa_1.b ),
    .B(_20_),
    .ZN(\fa_4_3.ripple[2].fa_1.sum )
  );
  OAI21_X1 _53_ (
    .A(\fa_4_3.ripple[2].fa_1.b ),
    .B1(\fa_4_3.ripple[1].fa_1.c_out ),
    .B2(\fa_4_3.ripple[2].fa_1.a ),
    .ZN(_21_)
  );
  NAND2_X1 _54_ (
    .A1(_19_),
    .A2(_21_),
    .ZN(\fa_4_3.ripple[2].fa_1.c_out )
  );
  NAND2_X1 _55_ (
    .A1(\fa_4_3.ripple[3].fa_1.a ),
    .A2(\fa_4_3.ripple[2].fa_1.c_out ),
    .ZN(_22_)
  );
  XNOR2_X1 _56_ (
    .A(\fa_4_3.ripple[3].fa_1.a ),
    .B(\fa_4_3.ripple[2].fa_1.c_out ),
    .ZN(_23_)
  );
  XNOR2_X1 _57_ (
    .A(\fa_4_3.ripple[3].fa_1.b ),
    .B(_23_),
    .ZN(\fa_4_3.ripple[3].fa_1.sum )
  );
  OAI21_X1 _58_ (
    .A(\fa_4_3.ripple[3].fa_1.b ),
    .B1(\fa_4_3.ripple[2].fa_1.c_out ),
    .B2(\fa_4_3.ripple[3].fa_1.a ),
    .ZN(_24_)
  );
  NAND2_X1 _59_ (
    .A1(_22_),
    .A2(_24_),
    .ZN(\fa_4_3.C_out )
  );
  BUF_X2 _60_ (
    .A(_25_),
    .Z(C_out)
  );
  BUF_X2 _61_ (
    .A(_26_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _62_ (
    .A(_26_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _63_ (
    .A(_26_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _64_ (
    .A(_26_[3]),
    .Z(Sum[3])
  );
endmodule
