/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module CLA_N(A, B, clk, Sum, C_out);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  output C_out;
  wire C_out;
  output [3:0] Sum;
  wire [3:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire [3:0] _24_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  wire [3:0] \c1.A ;
  wire [3:0] \c1.B ;
  wire [3:0] \c1.C_sa ;
  wire [3:0] \c1.P ;
  wire [3:0] \c1.S ;
  input clk;
  wire clk;
  DFF_X1 _25_ (
    .CK(clk),
    .D(B[0]),
    .Q(\c1.B [0]),
    .QN(_1_)
  );
  DFF_X1 _26_ (
    .CK(clk),
    .D(B[1]),
    .Q(\c1.B [1]),
    .QN(_2_)
  );
  DFF_X1 _27_ (
    .CK(clk),
    .D(B[2]),
    .Q(\c1.B [2]),
    .QN(_3_)
  );
  DFF_X1 _28_ (
    .CK(clk),
    .D(B[3]),
    .Q(\c1.B [3]),
    .QN(_4_)
  );
  DFF_X1 _29_ (
    .CK(clk),
    .D(A[0]),
    .Q(\c1.A [0]),
    .QN(_5_)
  );
  DFF_X1 _30_ (
    .CK(clk),
    .D(A[1]),
    .Q(\c1.A [1]),
    .QN(_6_)
  );
  DFF_X1 _31_ (
    .CK(clk),
    .D(A[2]),
    .Q(\c1.A [2]),
    .QN(_7_)
  );
  DFF_X1 _32_ (
    .CK(clk),
    .D(A[3]),
    .Q(\c1.A [3]),
    .QN(_8_)
  );
  DFF_X1 _33_ (
    .CK(clk),
    .D(\c1.C_sa [3]),
    .Q(_23_),
    .QN(_9_)
  );
  DFF_X1 _34_ (
    .CK(clk),
    .D(\c1.P [0]),
    .Q(_24_[0]),
    .QN(_10_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(\c1.S [1]),
    .Q(_24_[1]),
    .QN(_11_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(\c1.S [2]),
    .Q(_24_[2]),
    .QN(_12_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(\c1.S [3]),
    .Q(_24_[3]),
    .QN(_0_)
  );
  NAND2_X1 _38_ (
    .A1(\c1.A [0]),
    .A2(\c1.B [0]),
    .ZN(_13_)
  );
  XOR2_X1 _39_ (
    .A(\c1.A [0]),
    .B(\c1.B [0]),
    .Z(\c1.P [0])
  );
  NAND2_X1 _40_ (
    .A1(\c1.A [1]),
    .A2(\c1.B [1]),
    .ZN(_14_)
  );
  NOR2_X1 _41_ (
    .A1(\c1.A [1]),
    .A2(\c1.B [1]),
    .ZN(_15_)
  );
  XOR2_X1 _42_ (
    .A(\c1.A [1]),
    .B(\c1.B [1]),
    .Z(_16_)
  );
  OAI21_X1 _43_ (
    .A(_14_),
    .B1(_15_),
    .B2(_13_),
    .ZN(\c1.C_sa [1])
  );
  AND2_X1 _44_ (
    .A1(\c1.A [2]),
    .A2(\c1.B [2]),
    .ZN(_17_)
  );
  XOR2_X1 _45_ (
    .A(\c1.A [2]),
    .B(\c1.B [2]),
    .Z(_18_)
  );
  AOI21_X1 _46_ (
    .A(_17_),
    .B1(_18_),
    .B2(\c1.C_sa [1]),
    .ZN(_19_)
  );
  NAND2_X1 _47_ (
    .A1(\c1.A [3]),
    .A2(\c1.B [3]),
    .ZN(_20_)
  );
  NOR2_X1 _48_ (
    .A1(\c1.A [3]),
    .A2(\c1.B [3]),
    .ZN(_21_)
  );
  XOR2_X1 _49_ (
    .A(\c1.A [3]),
    .B(\c1.B [3]),
    .Z(_22_)
  );
  OAI21_X1 _50_ (
    .A(_20_),
    .B1(_21_),
    .B2(_19_),
    .ZN(\c1.C_sa [3])
  );
  XNOR2_X1 _51_ (
    .A(_13_),
    .B(_16_),
    .ZN(\c1.S [1])
  );
  XOR2_X1 _52_ (
    .A(\c1.C_sa [1]),
    .B(_18_),
    .Z(\c1.S [2])
  );
  XNOR2_X1 _53_ (
    .A(_19_),
    .B(_22_),
    .ZN(\c1.S [3])
  );
  BUF_X2 _54_ (
    .A(_23_),
    .Z(C_out)
  );
  BUF_X2 _55_ (
    .A(_24_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _56_ (
    .A(_24_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _57_ (
    .A(_24_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _58_ (
    .A(_24_[3]),
    .Z(Sum[3])
  );
  assign \c1.S [0] = \c1.P [0];
endmodule
