/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module seq_detect(x, clk, rst, y);
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input clk;
  wire clk;
  input rst;
  wire rst;
  wire [2:0] state;
  input x;
  wire x;
  output y;
  wire y;
  INV_X1 _19_ (
    .A(x),
    .ZN(_6_)
  );
  NOR3_X1 _20_ (
    .A1(_2_),
    .A2(state[0]),
    .A3(_1_),
    .ZN(_7_)
  );
  NOR3_X1 _21_ (
    .A1(_2_),
    .A2(_0_),
    .A3(state[1]),
    .ZN(_8_)
  );
  AOI211_X1 _22_ (
    .A(_0_),
    .B(state[2]),
    .C1(_1_),
    .C2(state[1]),
    .ZN(_9_)
  );
  NOR3_X1 _23_ (
    .A1(state[0]),
    .A2(_1_),
    .A3(state[2]),
    .ZN(_10_)
  );
  AOI221_X1 _24_ (
    .A(state[2]),
    .B1(_1_),
    .B2(state[1]),
    .C1(_0_),
    .C2(state[0]),
    .ZN(_11_)
  );
  NOR3_X1 _25_ (
    .A1(_7_),
    .A2(_8_),
    .A3(_11_),
    .ZN(_12_)
  );
  NOR4_X1 _26_ (
    .A1(_0_),
    .A2(_1_),
    .A3(state[2]),
    .A4(x),
    .ZN(_13_)
  );
  AOI211_X1 _27_ (
    .A(_10_),
    .B(_13_),
    .C1(x),
    .C2(_7_),
    .ZN(_14_)
  );
  NOR3_X1 _28_ (
    .A1(rst),
    .A2(_12_),
    .A3(_14_),
    .ZN(_3_)
  );
  AOI21_X1 _29_ (
    .A(_9_),
    .B1(_8_),
    .B2(x),
    .ZN(_15_)
  );
  NOR3_X1 _30_ (
    .A1(rst),
    .A2(_12_),
    .A3(_15_),
    .ZN(_4_)
  );
  NOR3_X1 _31_ (
    .A1(rst),
    .A2(_6_),
    .A3(_12_),
    .ZN(_5_)
  );
  OR3_X1 _32_ (
    .A1(_2_),
    .A2(state[1]),
    .A3(state[0]),
    .ZN(_16_)
  );
  NOR3_X1 _33_ (
    .A1(x),
    .A2(_7_),
    .A3(_8_),
    .ZN(_17_)
  );
  AOI21_X1 _34_ (
    .A(_17_),
    .B1(_16_),
    .B2(x),
    .ZN(_18_)
  );
  DFF_X1 _35_ (
    .CK(clk),
    .D(_3_),
    .Q(state[2]),
    .QN(_2_)
  );
  DFF_X1 _36_ (
    .CK(clk),
    .D(_4_),
    .Q(state[1]),
    .QN(_1_)
  );
  DFF_X1 _37_ (
    .CK(clk),
    .D(_5_),
    .Q(state[0]),
    .QN(_0_)
  );
  BUF_X2 _38_ (
    .A(_18_),
    .Z(y)
  );
endmodule
