/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module RCA_N(A, B, clk, Sum, C_out);
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  output C_out;
  wire C_out;
  output [15:0] Sum;
  wire [15:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire [15:0] _98_;
  wire _9_;
  input clk;
  wire clk;
  wire \ripple[0].fa_1.a ;
  wire \ripple[0].fa_1.b ;
  wire \ripple[0].fa_1.c_out ;
  wire \ripple[0].fa_1.sum ;
  wire \ripple[10].fa_1.a ;
  wire \ripple[10].fa_1.b ;
  wire \ripple[10].fa_1.c_in ;
  wire \ripple[10].fa_1.c_out ;
  wire \ripple[10].fa_1.sum ;
  wire \ripple[11].fa_1.a ;
  wire \ripple[11].fa_1.b ;
  wire \ripple[11].fa_1.c_out ;
  wire \ripple[11].fa_1.sum ;
  wire \ripple[12].fa_1.a ;
  wire \ripple[12].fa_1.b ;
  wire \ripple[12].fa_1.c_out ;
  wire \ripple[12].fa_1.sum ;
  wire \ripple[13].fa_1.a ;
  wire \ripple[13].fa_1.b ;
  wire \ripple[13].fa_1.c_out ;
  wire \ripple[13].fa_1.sum ;
  wire \ripple[14].fa_1.a ;
  wire \ripple[14].fa_1.b ;
  wire \ripple[14].fa_1.c_out ;
  wire \ripple[14].fa_1.sum ;
  wire \ripple[15].fa_1.a ;
  wire \ripple[15].fa_1.b ;
  wire \ripple[15].fa_1.c_out ;
  wire \ripple[15].fa_1.sum ;
  wire \ripple[1].fa_1.a ;
  wire \ripple[1].fa_1.b ;
  wire \ripple[1].fa_1.c_out ;
  wire \ripple[1].fa_1.sum ;
  wire \ripple[2].fa_1.a ;
  wire \ripple[2].fa_1.b ;
  wire \ripple[2].fa_1.c_out ;
  wire \ripple[2].fa_1.sum ;
  wire \ripple[3].fa_1.a ;
  wire \ripple[3].fa_1.b ;
  wire \ripple[3].fa_1.c_out ;
  wire \ripple[3].fa_1.sum ;
  wire \ripple[4].fa_1.a ;
  wire \ripple[4].fa_1.b ;
  wire \ripple[4].fa_1.c_out ;
  wire \ripple[4].fa_1.sum ;
  wire \ripple[5].fa_1.a ;
  wire \ripple[5].fa_1.b ;
  wire \ripple[5].fa_1.c_out ;
  wire \ripple[5].fa_1.sum ;
  wire \ripple[6].fa_1.a ;
  wire \ripple[6].fa_1.b ;
  wire \ripple[6].fa_1.c_out ;
  wire \ripple[6].fa_1.sum ;
  wire \ripple[7].fa_1.a ;
  wire \ripple[7].fa_1.b ;
  wire \ripple[7].fa_1.c_out ;
  wire \ripple[7].fa_1.sum ;
  wire \ripple[8].fa_1.a ;
  wire \ripple[8].fa_1.b ;
  wire \ripple[8].fa_1.c_out ;
  wire \ripple[8].fa_1.sum ;
  wire \ripple[9].fa_1.a ;
  wire \ripple[9].fa_1.b ;
  wire \ripple[9].fa_1.sum ;
  DFF_X1 _100_ (
    .CK(clk),
    .D(\ripple[11].fa_1.sum ),
    .Q(_98_[11]),
    .QN(_2_)
  );
  DFF_X1 _101_ (
    .CK(clk),
    .D(\ripple[12].fa_1.sum ),
    .Q(_98_[12]),
    .QN(_3_)
  );
  DFF_X1 _102_ (
    .CK(clk),
    .D(\ripple[13].fa_1.sum ),
    .Q(_98_[13]),
    .QN(_4_)
  );
  DFF_X1 _103_ (
    .CK(clk),
    .D(\ripple[14].fa_1.sum ),
    .Q(_98_[14]),
    .QN(_5_)
  );
  DFF_X1 _104_ (
    .CK(clk),
    .D(\ripple[15].fa_1.sum ),
    .Q(_98_[15]),
    .QN(_6_)
  );
  DFF_X1 _105_ (
    .CK(clk),
    .D(\ripple[15].fa_1.c_out ),
    .Q(_97_),
    .QN(_7_)
  );
  DFF_X1 _106_ (
    .CK(clk),
    .D(A[0]),
    .Q(\ripple[0].fa_1.a ),
    .QN(_8_)
  );
  DFF_X1 _107_ (
    .CK(clk),
    .D(A[1]),
    .Q(\ripple[1].fa_1.a ),
    .QN(_9_)
  );
  DFF_X1 _108_ (
    .CK(clk),
    .D(A[2]),
    .Q(\ripple[2].fa_1.a ),
    .QN(_10_)
  );
  DFF_X1 _109_ (
    .CK(clk),
    .D(A[3]),
    .Q(\ripple[3].fa_1.a ),
    .QN(_11_)
  );
  DFF_X1 _110_ (
    .CK(clk),
    .D(A[4]),
    .Q(\ripple[4].fa_1.a ),
    .QN(_12_)
  );
  DFF_X1 _111_ (
    .CK(clk),
    .D(A[5]),
    .Q(\ripple[5].fa_1.a ),
    .QN(_13_)
  );
  DFF_X1 _112_ (
    .CK(clk),
    .D(A[6]),
    .Q(\ripple[6].fa_1.a ),
    .QN(_14_)
  );
  DFF_X1 _113_ (
    .CK(clk),
    .D(A[7]),
    .Q(\ripple[7].fa_1.a ),
    .QN(_15_)
  );
  DFF_X1 _114_ (
    .CK(clk),
    .D(A[8]),
    .Q(\ripple[8].fa_1.a ),
    .QN(_16_)
  );
  DFF_X1 _115_ (
    .CK(clk),
    .D(A[9]),
    .Q(\ripple[9].fa_1.a ),
    .QN(_17_)
  );
  DFF_X1 _116_ (
    .CK(clk),
    .D(A[10]),
    .Q(\ripple[10].fa_1.a ),
    .QN(_18_)
  );
  DFF_X1 _117_ (
    .CK(clk),
    .D(A[11]),
    .Q(\ripple[11].fa_1.a ),
    .QN(_19_)
  );
  DFF_X1 _118_ (
    .CK(clk),
    .D(A[12]),
    .Q(\ripple[12].fa_1.a ),
    .QN(_20_)
  );
  DFF_X1 _119_ (
    .CK(clk),
    .D(A[13]),
    .Q(\ripple[13].fa_1.a ),
    .QN(_21_)
  );
  DFF_X1 _120_ (
    .CK(clk),
    .D(A[14]),
    .Q(\ripple[14].fa_1.a ),
    .QN(_22_)
  );
  DFF_X1 _121_ (
    .CK(clk),
    .D(A[15]),
    .Q(\ripple[15].fa_1.a ),
    .QN(_23_)
  );
  DFF_X1 _122_ (
    .CK(clk),
    .D(B[0]),
    .Q(\ripple[0].fa_1.b ),
    .QN(_24_)
  );
  DFF_X1 _123_ (
    .CK(clk),
    .D(B[1]),
    .Q(\ripple[1].fa_1.b ),
    .QN(_25_)
  );
  DFF_X1 _124_ (
    .CK(clk),
    .D(B[2]),
    .Q(\ripple[2].fa_1.b ),
    .QN(_26_)
  );
  DFF_X1 _125_ (
    .CK(clk),
    .D(B[3]),
    .Q(\ripple[3].fa_1.b ),
    .QN(_27_)
  );
  DFF_X1 _126_ (
    .CK(clk),
    .D(B[4]),
    .Q(\ripple[4].fa_1.b ),
    .QN(_28_)
  );
  DFF_X1 _127_ (
    .CK(clk),
    .D(B[5]),
    .Q(\ripple[5].fa_1.b ),
    .QN(_29_)
  );
  DFF_X1 _128_ (
    .CK(clk),
    .D(B[6]),
    .Q(\ripple[6].fa_1.b ),
    .QN(_30_)
  );
  DFF_X1 _129_ (
    .CK(clk),
    .D(B[7]),
    .Q(\ripple[7].fa_1.b ),
    .QN(_31_)
  );
  DFF_X1 _130_ (
    .CK(clk),
    .D(B[8]),
    .Q(\ripple[8].fa_1.b ),
    .QN(_32_)
  );
  DFF_X1 _131_ (
    .CK(clk),
    .D(B[9]),
    .Q(\ripple[9].fa_1.b ),
    .QN(_33_)
  );
  DFF_X1 _132_ (
    .CK(clk),
    .D(B[10]),
    .Q(\ripple[10].fa_1.b ),
    .QN(_34_)
  );
  DFF_X1 _133_ (
    .CK(clk),
    .D(B[11]),
    .Q(\ripple[11].fa_1.b ),
    .QN(_35_)
  );
  DFF_X1 _134_ (
    .CK(clk),
    .D(B[12]),
    .Q(\ripple[12].fa_1.b ),
    .QN(_36_)
  );
  DFF_X1 _135_ (
    .CK(clk),
    .D(B[13]),
    .Q(\ripple[13].fa_1.b ),
    .QN(_37_)
  );
  DFF_X1 _136_ (
    .CK(clk),
    .D(B[14]),
    .Q(\ripple[14].fa_1.b ),
    .QN(_38_)
  );
  DFF_X1 _137_ (
    .CK(clk),
    .D(B[15]),
    .Q(\ripple[15].fa_1.b ),
    .QN(_39_)
  );
  DFF_X1 _138_ (
    .CK(clk),
    .D(\ripple[0].fa_1.sum ),
    .Q(_98_[0]),
    .QN(_40_)
  );
  DFF_X1 _139_ (
    .CK(clk),
    .D(\ripple[1].fa_1.sum ),
    .Q(_98_[1]),
    .QN(_41_)
  );
  DFF_X1 _140_ (
    .CK(clk),
    .D(\ripple[2].fa_1.sum ),
    .Q(_98_[2]),
    .QN(_42_)
  );
  DFF_X1 _141_ (
    .CK(clk),
    .D(\ripple[3].fa_1.sum ),
    .Q(_98_[3]),
    .QN(_43_)
  );
  DFF_X1 _142_ (
    .CK(clk),
    .D(\ripple[4].fa_1.sum ),
    .Q(_98_[4]),
    .QN(_44_)
  );
  DFF_X1 _143_ (
    .CK(clk),
    .D(\ripple[5].fa_1.sum ),
    .Q(_98_[5]),
    .QN(_45_)
  );
  DFF_X1 _144_ (
    .CK(clk),
    .D(\ripple[6].fa_1.sum ),
    .Q(_98_[6]),
    .QN(_46_)
  );
  DFF_X1 _145_ (
    .CK(clk),
    .D(\ripple[7].fa_1.sum ),
    .Q(_98_[7]),
    .QN(_47_)
  );
  DFF_X1 _146_ (
    .CK(clk),
    .D(\ripple[8].fa_1.sum ),
    .Q(_98_[8]),
    .QN(_48_)
  );
  DFF_X1 _147_ (
    .CK(clk),
    .D(\ripple[9].fa_1.sum ),
    .Q(_98_[9]),
    .QN(_0_)
  );
  NAND2_X1 _148_ (
    .A1(\ripple[0].fa_1.a ),
    .A2(1'h0),
    .ZN(_49_)
  );
  XNOR2_X1 _149_ (
    .A(\ripple[0].fa_1.a ),
    .B(1'h0),
    .ZN(_50_)
  );
  XNOR2_X1 _150_ (
    .A(\ripple[0].fa_1.b ),
    .B(_50_),
    .ZN(\ripple[0].fa_1.sum )
  );
  OAI21_X1 _151_ (
    .A(\ripple[0].fa_1.b ),
    .B1(1'h0),
    .B2(\ripple[0].fa_1.a ),
    .ZN(_51_)
  );
  NAND2_X1 _152_ (
    .A1(_49_),
    .A2(_51_),
    .ZN(\ripple[0].fa_1.c_out )
  );
  NAND2_X1 _153_ (
    .A1(\ripple[10].fa_1.a ),
    .A2(\ripple[10].fa_1.c_in ),
    .ZN(_52_)
  );
  XNOR2_X1 _154_ (
    .A(\ripple[10].fa_1.a ),
    .B(\ripple[10].fa_1.c_in ),
    .ZN(_53_)
  );
  XNOR2_X1 _155_ (
    .A(\ripple[10].fa_1.b ),
    .B(_53_),
    .ZN(\ripple[10].fa_1.sum )
  );
  OAI21_X1 _156_ (
    .A(\ripple[10].fa_1.b ),
    .B1(\ripple[10].fa_1.c_in ),
    .B2(\ripple[10].fa_1.a ),
    .ZN(_54_)
  );
  NAND2_X1 _157_ (
    .A1(_52_),
    .A2(_54_),
    .ZN(\ripple[10].fa_1.c_out )
  );
  NAND2_X1 _158_ (
    .A1(\ripple[11].fa_1.a ),
    .A2(\ripple[10].fa_1.c_out ),
    .ZN(_55_)
  );
  XNOR2_X1 _159_ (
    .A(\ripple[11].fa_1.a ),
    .B(\ripple[10].fa_1.c_out ),
    .ZN(_56_)
  );
  XNOR2_X1 _160_ (
    .A(\ripple[11].fa_1.b ),
    .B(_56_),
    .ZN(\ripple[11].fa_1.sum )
  );
  OAI21_X1 _161_ (
    .A(\ripple[11].fa_1.b ),
    .B1(\ripple[10].fa_1.c_out ),
    .B2(\ripple[11].fa_1.a ),
    .ZN(_57_)
  );
  NAND2_X1 _162_ (
    .A1(_55_),
    .A2(_57_),
    .ZN(\ripple[11].fa_1.c_out )
  );
  NAND2_X1 _163_ (
    .A1(\ripple[12].fa_1.a ),
    .A2(\ripple[11].fa_1.c_out ),
    .ZN(_58_)
  );
  XNOR2_X1 _164_ (
    .A(\ripple[12].fa_1.a ),
    .B(\ripple[11].fa_1.c_out ),
    .ZN(_59_)
  );
  XNOR2_X1 _165_ (
    .A(\ripple[12].fa_1.b ),
    .B(_59_),
    .ZN(\ripple[12].fa_1.sum )
  );
  OAI21_X1 _166_ (
    .A(\ripple[12].fa_1.b ),
    .B1(\ripple[11].fa_1.c_out ),
    .B2(\ripple[12].fa_1.a ),
    .ZN(_60_)
  );
  NAND2_X1 _167_ (
    .A1(_58_),
    .A2(_60_),
    .ZN(\ripple[12].fa_1.c_out )
  );
  NAND2_X1 _168_ (
    .A1(\ripple[13].fa_1.a ),
    .A2(\ripple[12].fa_1.c_out ),
    .ZN(_61_)
  );
  XNOR2_X1 _169_ (
    .A(\ripple[13].fa_1.a ),
    .B(\ripple[12].fa_1.c_out ),
    .ZN(_62_)
  );
  XNOR2_X1 _170_ (
    .A(\ripple[13].fa_1.b ),
    .B(_62_),
    .ZN(\ripple[13].fa_1.sum )
  );
  OAI21_X1 _171_ (
    .A(\ripple[13].fa_1.b ),
    .B1(\ripple[12].fa_1.c_out ),
    .B2(\ripple[13].fa_1.a ),
    .ZN(_63_)
  );
  NAND2_X1 _172_ (
    .A1(_61_),
    .A2(_63_),
    .ZN(\ripple[13].fa_1.c_out )
  );
  NAND2_X1 _173_ (
    .A1(\ripple[14].fa_1.a ),
    .A2(\ripple[13].fa_1.c_out ),
    .ZN(_64_)
  );
  XNOR2_X1 _174_ (
    .A(\ripple[14].fa_1.a ),
    .B(\ripple[13].fa_1.c_out ),
    .ZN(_65_)
  );
  XNOR2_X1 _175_ (
    .A(\ripple[14].fa_1.b ),
    .B(_65_),
    .ZN(\ripple[14].fa_1.sum )
  );
  OAI21_X1 _176_ (
    .A(\ripple[14].fa_1.b ),
    .B1(\ripple[13].fa_1.c_out ),
    .B2(\ripple[14].fa_1.a ),
    .ZN(_66_)
  );
  NAND2_X1 _177_ (
    .A1(_64_),
    .A2(_66_),
    .ZN(\ripple[14].fa_1.c_out )
  );
  NAND2_X1 _178_ (
    .A1(\ripple[15].fa_1.a ),
    .A2(\ripple[14].fa_1.c_out ),
    .ZN(_67_)
  );
  XNOR2_X1 _179_ (
    .A(\ripple[15].fa_1.a ),
    .B(\ripple[14].fa_1.c_out ),
    .ZN(_68_)
  );
  XNOR2_X1 _180_ (
    .A(\ripple[15].fa_1.b ),
    .B(_68_),
    .ZN(\ripple[15].fa_1.sum )
  );
  OAI21_X1 _181_ (
    .A(\ripple[15].fa_1.b ),
    .B1(\ripple[14].fa_1.c_out ),
    .B2(\ripple[15].fa_1.a ),
    .ZN(_69_)
  );
  NAND2_X1 _182_ (
    .A1(_67_),
    .A2(_69_),
    .ZN(\ripple[15].fa_1.c_out )
  );
  NAND2_X1 _183_ (
    .A1(\ripple[1].fa_1.a ),
    .A2(\ripple[0].fa_1.c_out ),
    .ZN(_70_)
  );
  XNOR2_X1 _184_ (
    .A(\ripple[1].fa_1.a ),
    .B(\ripple[0].fa_1.c_out ),
    .ZN(_71_)
  );
  XNOR2_X1 _185_ (
    .A(\ripple[1].fa_1.b ),
    .B(_71_),
    .ZN(\ripple[1].fa_1.sum )
  );
  OAI21_X1 _186_ (
    .A(\ripple[1].fa_1.b ),
    .B1(\ripple[0].fa_1.c_out ),
    .B2(\ripple[1].fa_1.a ),
    .ZN(_72_)
  );
  NAND2_X1 _187_ (
    .A1(_70_),
    .A2(_72_),
    .ZN(\ripple[1].fa_1.c_out )
  );
  NAND2_X1 _188_ (
    .A1(\ripple[2].fa_1.a ),
    .A2(\ripple[1].fa_1.c_out ),
    .ZN(_73_)
  );
  XNOR2_X1 _189_ (
    .A(\ripple[2].fa_1.a ),
    .B(\ripple[1].fa_1.c_out ),
    .ZN(_74_)
  );
  XNOR2_X1 _190_ (
    .A(\ripple[2].fa_1.b ),
    .B(_74_),
    .ZN(\ripple[2].fa_1.sum )
  );
  OAI21_X1 _191_ (
    .A(\ripple[2].fa_1.b ),
    .B1(\ripple[1].fa_1.c_out ),
    .B2(\ripple[2].fa_1.a ),
    .ZN(_75_)
  );
  NAND2_X1 _192_ (
    .A1(_73_),
    .A2(_75_),
    .ZN(\ripple[2].fa_1.c_out )
  );
  NAND2_X1 _193_ (
    .A1(\ripple[3].fa_1.a ),
    .A2(\ripple[2].fa_1.c_out ),
    .ZN(_76_)
  );
  XNOR2_X1 _194_ (
    .A(\ripple[3].fa_1.a ),
    .B(\ripple[2].fa_1.c_out ),
    .ZN(_77_)
  );
  XNOR2_X1 _195_ (
    .A(\ripple[3].fa_1.b ),
    .B(_77_),
    .ZN(\ripple[3].fa_1.sum )
  );
  OAI21_X1 _196_ (
    .A(\ripple[3].fa_1.b ),
    .B1(\ripple[2].fa_1.c_out ),
    .B2(\ripple[3].fa_1.a ),
    .ZN(_78_)
  );
  NAND2_X1 _197_ (
    .A1(_76_),
    .A2(_78_),
    .ZN(\ripple[3].fa_1.c_out )
  );
  NAND2_X1 _198_ (
    .A1(\ripple[4].fa_1.a ),
    .A2(\ripple[3].fa_1.c_out ),
    .ZN(_79_)
  );
  XNOR2_X1 _199_ (
    .A(\ripple[4].fa_1.a ),
    .B(\ripple[3].fa_1.c_out ),
    .ZN(_80_)
  );
  XNOR2_X1 _200_ (
    .A(\ripple[4].fa_1.b ),
    .B(_80_),
    .ZN(\ripple[4].fa_1.sum )
  );
  OAI21_X1 _201_ (
    .A(\ripple[4].fa_1.b ),
    .B1(\ripple[3].fa_1.c_out ),
    .B2(\ripple[4].fa_1.a ),
    .ZN(_81_)
  );
  NAND2_X1 _202_ (
    .A1(_79_),
    .A2(_81_),
    .ZN(\ripple[4].fa_1.c_out )
  );
  NAND2_X1 _203_ (
    .A1(\ripple[5].fa_1.a ),
    .A2(\ripple[4].fa_1.c_out ),
    .ZN(_82_)
  );
  XNOR2_X1 _204_ (
    .A(\ripple[5].fa_1.a ),
    .B(\ripple[4].fa_1.c_out ),
    .ZN(_83_)
  );
  XNOR2_X1 _205_ (
    .A(\ripple[5].fa_1.b ),
    .B(_83_),
    .ZN(\ripple[5].fa_1.sum )
  );
  OAI21_X1 _206_ (
    .A(\ripple[5].fa_1.b ),
    .B1(\ripple[4].fa_1.c_out ),
    .B2(\ripple[5].fa_1.a ),
    .ZN(_84_)
  );
  NAND2_X1 _207_ (
    .A1(_82_),
    .A2(_84_),
    .ZN(\ripple[5].fa_1.c_out )
  );
  NAND2_X1 _208_ (
    .A1(\ripple[6].fa_1.a ),
    .A2(\ripple[5].fa_1.c_out ),
    .ZN(_85_)
  );
  XNOR2_X1 _209_ (
    .A(\ripple[6].fa_1.a ),
    .B(\ripple[5].fa_1.c_out ),
    .ZN(_86_)
  );
  XNOR2_X1 _210_ (
    .A(\ripple[6].fa_1.b ),
    .B(_86_),
    .ZN(\ripple[6].fa_1.sum )
  );
  OAI21_X1 _211_ (
    .A(\ripple[6].fa_1.b ),
    .B1(\ripple[5].fa_1.c_out ),
    .B2(\ripple[6].fa_1.a ),
    .ZN(_87_)
  );
  NAND2_X1 _212_ (
    .A1(_85_),
    .A2(_87_),
    .ZN(\ripple[6].fa_1.c_out )
  );
  NAND2_X1 _213_ (
    .A1(\ripple[7].fa_1.a ),
    .A2(\ripple[6].fa_1.c_out ),
    .ZN(_88_)
  );
  XNOR2_X1 _214_ (
    .A(\ripple[7].fa_1.a ),
    .B(\ripple[6].fa_1.c_out ),
    .ZN(_89_)
  );
  XNOR2_X1 _215_ (
    .A(\ripple[7].fa_1.b ),
    .B(_89_),
    .ZN(\ripple[7].fa_1.sum )
  );
  OAI21_X1 _216_ (
    .A(\ripple[7].fa_1.b ),
    .B1(\ripple[6].fa_1.c_out ),
    .B2(\ripple[7].fa_1.a ),
    .ZN(_90_)
  );
  NAND2_X1 _217_ (
    .A1(_88_),
    .A2(_90_),
    .ZN(\ripple[7].fa_1.c_out )
  );
  NAND2_X1 _218_ (
    .A1(\ripple[8].fa_1.a ),
    .A2(\ripple[7].fa_1.c_out ),
    .ZN(_91_)
  );
  XNOR2_X1 _219_ (
    .A(\ripple[8].fa_1.a ),
    .B(\ripple[7].fa_1.c_out ),
    .ZN(_92_)
  );
  XNOR2_X1 _220_ (
    .A(\ripple[8].fa_1.b ),
    .B(_92_),
    .ZN(\ripple[8].fa_1.sum )
  );
  OAI21_X1 _221_ (
    .A(\ripple[8].fa_1.b ),
    .B1(\ripple[7].fa_1.c_out ),
    .B2(\ripple[8].fa_1.a ),
    .ZN(_93_)
  );
  NAND2_X1 _222_ (
    .A1(_91_),
    .A2(_93_),
    .ZN(\ripple[8].fa_1.c_out )
  );
  NAND2_X1 _223_ (
    .A1(\ripple[9].fa_1.a ),
    .A2(\ripple[8].fa_1.c_out ),
    .ZN(_94_)
  );
  XNOR2_X1 _224_ (
    .A(\ripple[9].fa_1.a ),
    .B(\ripple[8].fa_1.c_out ),
    .ZN(_95_)
  );
  XNOR2_X1 _225_ (
    .A(\ripple[9].fa_1.b ),
    .B(_95_),
    .ZN(\ripple[9].fa_1.sum )
  );
  OAI21_X1 _226_ (
    .A(\ripple[9].fa_1.b ),
    .B1(\ripple[8].fa_1.c_out ),
    .B2(\ripple[9].fa_1.a ),
    .ZN(_96_)
  );
  NAND2_X1 _227_ (
    .A1(_94_),
    .A2(_96_),
    .ZN(\ripple[10].fa_1.c_in )
  );
  BUF_X2 _228_ (
    .A(_97_),
    .Z(C_out)
  );
  BUF_X2 _229_ (
    .A(_98_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _230_ (
    .A(_98_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _231_ (
    .A(_98_[10]),
    .Z(Sum[10])
  );
  BUF_X2 _232_ (
    .A(_98_[11]),
    .Z(Sum[11])
  );
  BUF_X2 _233_ (
    .A(_98_[12]),
    .Z(Sum[12])
  );
  BUF_X2 _234_ (
    .A(_98_[13]),
    .Z(Sum[13])
  );
  BUF_X2 _235_ (
    .A(_98_[14]),
    .Z(Sum[14])
  );
  BUF_X2 _236_ (
    .A(_98_[15]),
    .Z(Sum[15])
  );
  BUF_X2 _237_ (
    .A(_98_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _238_ (
    .A(_98_[3]),
    .Z(Sum[3])
  );
  BUF_X2 _239_ (
    .A(_98_[4]),
    .Z(Sum[4])
  );
  BUF_X2 _240_ (
    .A(_98_[5]),
    .Z(Sum[5])
  );
  BUF_X2 _241_ (
    .A(_98_[6]),
    .Z(Sum[6])
  );
  BUF_X2 _242_ (
    .A(_98_[7]),
    .Z(Sum[7])
  );
  BUF_X2 _243_ (
    .A(_98_[8]),
    .Z(Sum[8])
  );
  BUF_X2 _244_ (
    .A(_98_[9]),
    .Z(Sum[9])
  );
  DFF_X1 _99_ (
    .CK(clk),
    .D(\ripple[10].fa_1.sum ),
    .Q(_98_[10]),
    .QN(_1_)
  );
endmodule
