/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module RCA_N(A, B, clk, Sum, C_out);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  output C_out;
  wire C_out;
  output [7:0] Sum;
  wire [7:0] Sum;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire [7:0] _50_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input clk;
  wire clk;
  wire \ripple[0].fa_1.a ;
  wire \ripple[0].fa_1.b ;
  wire \ripple[0].fa_1.c_out ;
  wire \ripple[0].fa_1.sum ;
  wire \ripple[1].fa_1.a ;
  wire \ripple[1].fa_1.b ;
  wire \ripple[1].fa_1.c_out ;
  wire \ripple[1].fa_1.sum ;
  wire \ripple[2].fa_1.a ;
  wire \ripple[2].fa_1.b ;
  wire \ripple[2].fa_1.c_out ;
  wire \ripple[2].fa_1.sum ;
  wire \ripple[3].fa_1.a ;
  wire \ripple[3].fa_1.b ;
  wire \ripple[3].fa_1.c_out ;
  wire \ripple[3].fa_1.sum ;
  wire \ripple[4].fa_1.a ;
  wire \ripple[4].fa_1.b ;
  wire \ripple[4].fa_1.c_out ;
  wire \ripple[4].fa_1.sum ;
  wire \ripple[5].fa_1.a ;
  wire \ripple[5].fa_1.b ;
  wire \ripple[5].fa_1.c_out ;
  wire \ripple[5].fa_1.sum ;
  wire \ripple[6].fa_1.a ;
  wire \ripple[6].fa_1.b ;
  wire \ripple[6].fa_1.c_out ;
  wire \ripple[6].fa_1.sum ;
  wire \ripple[7].fa_1.a ;
  wire \ripple[7].fa_1.b ;
  wire \ripple[7].fa_1.c_out ;
  wire \ripple[7].fa_1.sum ;
  NAND2_X1 _100_ (
    .A1(_37_),
    .A2(_39_),
    .ZN(\ripple[4].fa_1.c_out )
  );
  NAND2_X1 _101_ (
    .A1(\ripple[5].fa_1.a ),
    .A2(\ripple[4].fa_1.c_out ),
    .ZN(_40_)
  );
  XNOR2_X1 _102_ (
    .A(\ripple[5].fa_1.a ),
    .B(\ripple[4].fa_1.c_out ),
    .ZN(_41_)
  );
  XNOR2_X1 _103_ (
    .A(\ripple[5].fa_1.b ),
    .B(_41_),
    .ZN(\ripple[5].fa_1.sum )
  );
  OAI21_X1 _104_ (
    .A(\ripple[5].fa_1.b ),
    .B1(\ripple[4].fa_1.c_out ),
    .B2(\ripple[5].fa_1.a ),
    .ZN(_42_)
  );
  NAND2_X1 _105_ (
    .A1(_40_),
    .A2(_42_),
    .ZN(\ripple[5].fa_1.c_out )
  );
  NAND2_X1 _106_ (
    .A1(\ripple[6].fa_1.a ),
    .A2(\ripple[5].fa_1.c_out ),
    .ZN(_43_)
  );
  XNOR2_X1 _107_ (
    .A(\ripple[6].fa_1.a ),
    .B(\ripple[5].fa_1.c_out ),
    .ZN(_44_)
  );
  XNOR2_X1 _108_ (
    .A(\ripple[6].fa_1.b ),
    .B(_44_),
    .ZN(\ripple[6].fa_1.sum )
  );
  OAI21_X1 _109_ (
    .A(\ripple[6].fa_1.b ),
    .B1(\ripple[5].fa_1.c_out ),
    .B2(\ripple[6].fa_1.a ),
    .ZN(_45_)
  );
  NAND2_X1 _110_ (
    .A1(_43_),
    .A2(_45_),
    .ZN(\ripple[6].fa_1.c_out )
  );
  NAND2_X1 _111_ (
    .A1(\ripple[7].fa_1.a ),
    .A2(\ripple[6].fa_1.c_out ),
    .ZN(_46_)
  );
  XNOR2_X1 _112_ (
    .A(\ripple[7].fa_1.a ),
    .B(\ripple[6].fa_1.c_out ),
    .ZN(_47_)
  );
  XNOR2_X1 _113_ (
    .A(\ripple[7].fa_1.b ),
    .B(_47_),
    .ZN(\ripple[7].fa_1.sum )
  );
  OAI21_X1 _114_ (
    .A(\ripple[7].fa_1.b ),
    .B1(\ripple[6].fa_1.c_out ),
    .B2(\ripple[7].fa_1.a ),
    .ZN(_48_)
  );
  NAND2_X1 _115_ (
    .A1(_46_),
    .A2(_48_),
    .ZN(\ripple[7].fa_1.c_out )
  );
  BUF_X2 _116_ (
    .A(_49_),
    .Z(C_out)
  );
  BUF_X2 _117_ (
    .A(_50_[0]),
    .Z(Sum[0])
  );
  BUF_X2 _118_ (
    .A(_50_[1]),
    .Z(Sum[1])
  );
  BUF_X2 _119_ (
    .A(_50_[2]),
    .Z(Sum[2])
  );
  BUF_X2 _120_ (
    .A(_50_[3]),
    .Z(Sum[3])
  );
  BUF_X2 _121_ (
    .A(_50_[4]),
    .Z(Sum[4])
  );
  BUF_X2 _122_ (
    .A(_50_[5]),
    .Z(Sum[5])
  );
  BUF_X2 _123_ (
    .A(_50_[6]),
    .Z(Sum[6])
  );
  BUF_X2 _124_ (
    .A(_50_[7]),
    .Z(Sum[7])
  );
  DFF_X1 _51_ (
    .CK(clk),
    .D(A[1]),
    .Q(\ripple[1].fa_1.a ),
    .QN(_1_)
  );
  DFF_X1 _52_ (
    .CK(clk),
    .D(A[2]),
    .Q(\ripple[2].fa_1.a ),
    .QN(_2_)
  );
  DFF_X1 _53_ (
    .CK(clk),
    .D(A[3]),
    .Q(\ripple[3].fa_1.a ),
    .QN(_3_)
  );
  DFF_X1 _54_ (
    .CK(clk),
    .D(A[4]),
    .Q(\ripple[4].fa_1.a ),
    .QN(_4_)
  );
  DFF_X1 _55_ (
    .CK(clk),
    .D(A[5]),
    .Q(\ripple[5].fa_1.a ),
    .QN(_5_)
  );
  DFF_X1 _56_ (
    .CK(clk),
    .D(A[6]),
    .Q(\ripple[6].fa_1.a ),
    .QN(_6_)
  );
  DFF_X1 _57_ (
    .CK(clk),
    .D(A[7]),
    .Q(\ripple[7].fa_1.a ),
    .QN(_7_)
  );
  DFF_X1 _58_ (
    .CK(clk),
    .D(B[0]),
    .Q(\ripple[0].fa_1.b ),
    .QN(_8_)
  );
  DFF_X1 _59_ (
    .CK(clk),
    .D(B[1]),
    .Q(\ripple[1].fa_1.b ),
    .QN(_9_)
  );
  DFF_X1 _60_ (
    .CK(clk),
    .D(B[2]),
    .Q(\ripple[2].fa_1.b ),
    .QN(_10_)
  );
  DFF_X1 _61_ (
    .CK(clk),
    .D(B[3]),
    .Q(\ripple[3].fa_1.b ),
    .QN(_11_)
  );
  DFF_X1 _62_ (
    .CK(clk),
    .D(B[4]),
    .Q(\ripple[4].fa_1.b ),
    .QN(_12_)
  );
  DFF_X1 _63_ (
    .CK(clk),
    .D(B[5]),
    .Q(\ripple[5].fa_1.b ),
    .QN(_13_)
  );
  DFF_X1 _64_ (
    .CK(clk),
    .D(B[6]),
    .Q(\ripple[6].fa_1.b ),
    .QN(_14_)
  );
  DFF_X1 _65_ (
    .CK(clk),
    .D(B[7]),
    .Q(\ripple[7].fa_1.b ),
    .QN(_15_)
  );
  DFF_X1 _66_ (
    .CK(clk),
    .D(\ripple[0].fa_1.sum ),
    .Q(_50_[0]),
    .QN(_16_)
  );
  DFF_X1 _67_ (
    .CK(clk),
    .D(\ripple[1].fa_1.sum ),
    .Q(_50_[1]),
    .QN(_17_)
  );
  DFF_X1 _68_ (
    .CK(clk),
    .D(\ripple[2].fa_1.sum ),
    .Q(_50_[2]),
    .QN(_18_)
  );
  DFF_X1 _69_ (
    .CK(clk),
    .D(\ripple[3].fa_1.sum ),
    .Q(_50_[3]),
    .QN(_19_)
  );
  DFF_X1 _70_ (
    .CK(clk),
    .D(\ripple[4].fa_1.sum ),
    .Q(_50_[4]),
    .QN(_20_)
  );
  DFF_X1 _71_ (
    .CK(clk),
    .D(\ripple[5].fa_1.sum ),
    .Q(_50_[5]),
    .QN(_21_)
  );
  DFF_X1 _72_ (
    .CK(clk),
    .D(\ripple[6].fa_1.sum ),
    .Q(_50_[6]),
    .QN(_22_)
  );
  DFF_X1 _73_ (
    .CK(clk),
    .D(\ripple[7].fa_1.sum ),
    .Q(_50_[7]),
    .QN(_23_)
  );
  DFF_X1 _74_ (
    .CK(clk),
    .D(\ripple[7].fa_1.c_out ),
    .Q(_49_),
    .QN(_24_)
  );
  DFF_X1 _75_ (
    .CK(clk),
    .D(A[0]),
    .Q(\ripple[0].fa_1.a ),
    .QN(_0_)
  );
  NAND2_X1 _76_ (
    .A1(\ripple[0].fa_1.a ),
    .A2(1'h0),
    .ZN(_25_)
  );
  XNOR2_X1 _77_ (
    .A(\ripple[0].fa_1.a ),
    .B(1'h0),
    .ZN(_26_)
  );
  XNOR2_X1 _78_ (
    .A(\ripple[0].fa_1.b ),
    .B(_26_),
    .ZN(\ripple[0].fa_1.sum )
  );
  OAI21_X1 _79_ (
    .A(\ripple[0].fa_1.b ),
    .B1(1'h0),
    .B2(\ripple[0].fa_1.a ),
    .ZN(_27_)
  );
  NAND2_X1 _80_ (
    .A1(_25_),
    .A2(_27_),
    .ZN(\ripple[0].fa_1.c_out )
  );
  NAND2_X1 _81_ (
    .A1(\ripple[1].fa_1.a ),
    .A2(\ripple[0].fa_1.c_out ),
    .ZN(_28_)
  );
  XNOR2_X1 _82_ (
    .A(\ripple[1].fa_1.a ),
    .B(\ripple[0].fa_1.c_out ),
    .ZN(_29_)
  );
  XNOR2_X1 _83_ (
    .A(\ripple[1].fa_1.b ),
    .B(_29_),
    .ZN(\ripple[1].fa_1.sum )
  );
  OAI21_X1 _84_ (
    .A(\ripple[1].fa_1.b ),
    .B1(\ripple[0].fa_1.c_out ),
    .B2(\ripple[1].fa_1.a ),
    .ZN(_30_)
  );
  NAND2_X1 _85_ (
    .A1(_28_),
    .A2(_30_),
    .ZN(\ripple[1].fa_1.c_out )
  );
  NAND2_X1 _86_ (
    .A1(\ripple[2].fa_1.a ),
    .A2(\ripple[1].fa_1.c_out ),
    .ZN(_31_)
  );
  XNOR2_X1 _87_ (
    .A(\ripple[2].fa_1.a ),
    .B(\ripple[1].fa_1.c_out ),
    .ZN(_32_)
  );
  XNOR2_X1 _88_ (
    .A(\ripple[2].fa_1.b ),
    .B(_32_),
    .ZN(\ripple[2].fa_1.sum )
  );
  OAI21_X1 _89_ (
    .A(\ripple[2].fa_1.b ),
    .B1(\ripple[1].fa_1.c_out ),
    .B2(\ripple[2].fa_1.a ),
    .ZN(_33_)
  );
  NAND2_X1 _90_ (
    .A1(_31_),
    .A2(_33_),
    .ZN(\ripple[2].fa_1.c_out )
  );
  NAND2_X1 _91_ (
    .A1(\ripple[3].fa_1.a ),
    .A2(\ripple[2].fa_1.c_out ),
    .ZN(_34_)
  );
  XNOR2_X1 _92_ (
    .A(\ripple[3].fa_1.a ),
    .B(\ripple[2].fa_1.c_out ),
    .ZN(_35_)
  );
  XNOR2_X1 _93_ (
    .A(\ripple[3].fa_1.b ),
    .B(_35_),
    .ZN(\ripple[3].fa_1.sum )
  );
  OAI21_X1 _94_ (
    .A(\ripple[3].fa_1.b ),
    .B1(\ripple[2].fa_1.c_out ),
    .B2(\ripple[3].fa_1.a ),
    .ZN(_36_)
  );
  NAND2_X1 _95_ (
    .A1(_34_),
    .A2(_36_),
    .ZN(\ripple[3].fa_1.c_out )
  );
  NAND2_X1 _96_ (
    .A1(\ripple[4].fa_1.a ),
    .A2(\ripple[3].fa_1.c_out ),
    .ZN(_37_)
  );
  XNOR2_X1 _97_ (
    .A(\ripple[4].fa_1.a ),
    .B(\ripple[3].fa_1.c_out ),
    .ZN(_38_)
  );
  XNOR2_X1 _98_ (
    .A(\ripple[4].fa_1.b ),
    .B(_38_),
    .ZN(\ripple[4].fa_1.sum )
  );
  OAI21_X1 _99_ (
    .A(\ripple[4].fa_1.b ),
    .B1(\ripple[3].fa_1.c_out ),
    .B2(\ripple[4].fa_1.a ),
    .ZN(_39_)
  );
endmodule
